### PR TITLE
Update master php testing versions

### LINKED ISSUE #58: Replace drone with github actions
Please migrate your drone usage to github actions

Seems you are using both so time to get rid of the drone part

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #58

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by nickvergessen** [comment]
> PHP Fatal error:  Could not check compatibility between PHPUnit\PharIo\Manifest\AuthorCollection::getIterator(): PHPUnit\PharIo\Manifest\AuthorCollectionIterator and IteratorAggregate::getIterator(): Traversable, because class PHPUnit\PharIo\Manifest\AuthorCollectionIterator is not available in phar:///usr/local/bin/phpunit/phar-io-manifest/values/AuthorCollection.php on line 33
Error: Process completed with exit code 255.

PHPUnit version is pinned to incompatible version

**Comment by come-nc** [comment]
@nickvergessen Not sure if the drone step can be removed? What about scrutinizer?

**Comment by come-nc** [comment]
@nickvergessen is `php-parallel-lint/php-parallel-lint` still a dev requirement?

**Review by blizzz — APPROVED** [review]

**Comment by nickvergessen** [comment]
> [nickvergessen](https://github.com/nickvergessen) is php-parallel-lint/php-parallel-lint still a dev requirement?

Removed

**Pull request merged**
